core/network/src/peer_manager/mod.rs

chore
adjust network info log level output for debug
Fixes #

chore(network): adjust default log level output

---

core/network/src/peer_manager/mod.rs

fix
- never reconnect bootstrap again after failure
- no peers warning when it's empty
Fixes #

fix(network): never reconnect bootstrap again after failure

---

Cargo.lock
core/api/src/adapter/mod.rs
core/api/src/lib.rs
core/consensus/src/fixed_types.rs
core/executor/src/cycles.rs
core/executor/src/lib.rs
core/executor/src/native_contract/account.rs
core/executor/src/native_contract/bank.rs
core/executor/src/tests/account_contract.rs
core/executor/src/tests/bank_contract.rs
core/executor/src/tests/mod.rs
protocol/src/traits/api.rs
protocol/src/traits/executor/mod.rs
src/main.rs

feature and fix
- GraphQL: get the asset balance of an account.
- The fixed panic that can occur when executor processes transfer balance.
Fixes #

feat: Get balance.

---

Makefile
core/api/src/lib.rs
core/api/src/schema/epoch.rs
core/api/src/schema/mod.rs
core/api/src/schema/transaction.rs
docs/build/gql_api.sh
docs/graphql_api.md

doc
Supports auto generating docs
Fixes #

doc: auto gen api

---

Cargo.lock
core/binding/Cargo.toml
core/binding/src/lib.rs
core/binding/src/state/mod.rs
core/binding/src/state/trie.rs
core/binding/src/state/trie_db.rs
core/binding/src/tests/mod.rs
core/binding/src/tests/state.rs
protocol/src/lib.rs
protocol/src/traits/executor.rs
protocol/src/traits/mod.rs

Feature
An implementation of the `service state` and its dependencies:
- `ServiceState`:  Provides a high-level API for `Service` to access the `world state`
- `MPTTrie`:  A wrapper for `cita_trie::Trie`.
- `TrieDB`: `Rocksdb` implementation of `cita_trie::DB`.
Fixes #

[ᚬframework] feat(core/binding): Implementation of service state.

---

Cargo.lock
Cargo.toml
core/binding-macro/Cargo.toml
core/binding-macro/src/lib.rs
core/binding-macro/src/read_write.rs
core/binding-macro/tests/mod.rs

Feature
Add `#[read]` and `#[write]` macros to mark methods that can be accessed.
At the same time, the `#[read]` and `#[write]` macros will also do some basic verification of the `method` signature to ensure that the `method` meets the expectations of the framework.
Fixes #
See the comments for a detailed explanation of the validation logic.  `core/binding-macro/src/lib.rs`

[ᚬframework] feat(core/binding-macro): Add `read` and `write` proc-macro.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

chore
tips for running `make ci` before create PR
Fixes #

chore: tips for running `make ci` before create PR

---

Cargo.lock
core/binding-macro/Cargo.toml
core/binding-macro/src/lib.rs
core/binding-macro/src/read_write.rs
core/binding-macro/src/servive.rs
core/binding-macro/tests/mod.rs
core/binding/Cargo.toml
core/binding/src/lib.rs
core/binding/src/request_context.rs
core/binding/src/sdk/mod.rs
core/binding/src/tests/request_context.rs
core/binding/src/tests/sdk.rs
protocol/src/traits/binding.rs

Feature
`#[service]` will automatically implement trait `protocol::traits::Service` and enrich its 4 methods (`hook_before_`、`hook_after_`、`write_`、`read_`).
- #[read]: accessible via `read_`.
- #[write]: accessible via `write_`.
- #[hook_before]: when calling `hook_before_`, it is actually calling a method with the attribute `#[hook_before]`
- #[hook_after]: when calling `hook_after_`, it is actually calling a method with the attribute `#[hook_after]`.
Fixes #
The main code logic is in `core/binding-macro/src/servive.rs`, you can look at `core/binding-macro/tests/mod.rs#test_impl_service` first and learn how to use it.
You can also view the expanded …

[ᚬframework] feat(core/binding-macro): Add #[service] to automatically implement the service trait.

---

binding-macro/src/lib.rs
binding-macro/src/read_write.rs
binding-macro/src/servive.rs
binding-macro/tests/mod.rs

feature
Return structs are supported, but `serde::Deserialize` and `serde::Serialize` must be added to `Derive`.
such as
```rust
#[derive(Deserialize, Serialize, Clone)]
pub struct GetBalancePayload {
pub asset_id: Hash,
}
#[service]
impl<SDK: ServiceSDK> AssetService<SDK> {
#[read]
fn get_balance<Context: RequestContext>(
&self,
ctx: Context,
payload: GetBalancePayload,
) -> ProtocolResult<GetBalanceResponse> {
let balance = self
.sdk
.get_account_value(&ctx.get_caller(), &payload.asset_id)?
.unwrap_or(0);
Ok(GetBalanceResponse {
asset_id: payload.asset_id,
balance,
})
}
}
```
Fixes #

[ᚬframework] feat(core/binding-macro): Support for returning a struct.

---

built-in-services/asset/src/lib.rs
framework/src/binding/store/array.rs
framework/src/binding/store/map.rs
framework/src/binding/store/primitive.rs
framework/src/binding/tests/sdk.rs
framework/src/binding/tests/store.rs
protocol/src/fixed_codec/mod.rs
protocol/src/fixed_codec/primitive.rs
protocol/src/fixed_codec/tests/fixed_codec.rs
protocol/src/traits/binding.rs

add feat(framework/binding)
1. Add Iterator for StoreMap and StoreArray
```rust
pub trait StoreMap<Key: FixedCodec + PartialEq, Value: FixedCodec> {
fn iter<'a>(&'a self) -> Box<dyn Iterator<Item = (&Key, Value)> + 'a>;
}
pub trait StoreArray<Elm: FixedCodec> {
fn iter<'a>(&'a self) -> Box<dyn Iterator<Item = (u32, Elm)> + 'a>;
}
```
2. Impl FixedCodec for u8, u32, u64, bool, String
Fixes #

[ᚬframework] feat(framework/binding): add Iterator and impl FixedCodec for rust primitive type

---

Cargo.lock
core/network/Cargo.toml
core/network/src/message/mod.rs
protocol/Cargo.toml
protocol/src/codec/epoch.rs
protocol/src/codec/mod.rs
protocol/src/codec/primitive.rs
protocol/src/codec/receipt.rs
protocol/src/codec/transaction.rs

chore
Replace git prost with muta-vendor-prost for bytes 0.5 support.
Fixes #

[ᚬmaster] chore: replace prost with muta-vendor-prost for bytes 0.5

---

binding-macro/tests/mod.rs
built-in-services/asset/src/tests/mod.rs
framework/Cargo.toml
framework/src/binding/sdk/mod.rs
framework/src/binding/tests/sdk.rs
framework/src/executor/mod.rs
framework/src/executor/tests/mod.rs
framework/src/executor/tests/service_call_service.rs
protocol/src/traits/binding.rs
protocol/src/traits/executor.rs
protocol/src/traits/mod.rs
src/default_start.rs

add framework feature: service call service
using ServiceSDK call another service is supported now
```rust
pub trait ServiceSDK {
fn read(
&self,
ctx: &ServiceContext,
service: &str,
method: &str,
payload: &str,
) -> ProtocolResult<String>;
fn write(
&mut self,
ctx: &ServiceContext,
service: &str,
method: &str,
payload: &str,
) -> ProtocolResult<String>;
... ...
}
```
Fixes #
- path of tests:  framework/src/executor/tests/service_call_service.rs

[ᚬmaster] feat(framework): add service-call-service feature

---

devtools/keypair/Cargo.toml
devtools/keypair/src/keypair.yml
devtools/keypair/src/main.rs

feature
Add another method to generate key pairs. Now the tool can generate keypairs from a given vector of secp256k1 private keys. If the given keys number is larger than the value of argument `-n`, the program will panic.
Fixes #

[ᚬmaster] feat(keypair): add another generate keypair arg

---

common/logger/src/lib.rs
devtools/chain/config.toml
src/config.rs
src/lib.rs

New feature.
Support specify module log level via config.
you can specify log level for modules like below:
```toml
[logger]
modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }
```
It is backward compatible. Configs without the key will be default value.
Fixes #

feat: support specify module log level via config

---

binding-macro/tests/mod.rs
built-in-services/asset/src/tests/mod.rs
framework/src/executor/mod.rs
protocol/src/types/service_context.rs

feat(framework)
add tx_hash, nonce to `ServiceContext`, which can be used by `Service`
Fixes #
```rust
impl ServiceContext {
pub fn get_tx_hash(&self) -> Option<Hash>;
pub fn get_nonce(&self) -> Option<Hash>;
}
```

feat(framework): add tx_hash, nonce to ServiceContext

---

binding-macro/src/common.rs
binding-macro/src/hooks.rs
binding-macro/src/lib.rs
binding-macro/src/read_write.rs
binding-macro/src/service.rs
binding-macro/tests/mod.rs
built-in-services/asset/src/lib.rs
framework/src/executor/mod.rs
protocol/src/traits/binding.rs

feat(framework)
Add `ExecutorParams` into hook method, so `Service` can get `epoch_id`, `timestamp`... in hook method
Fixes #
```rust
pub trait Service {
// Executed before the epoch is executed.
fn hook_before_(&mut self, params: &ExecutorParams) -> ProtocolResult<()> {
Ok(())
}
// Executed after epoch execution.
fn hook_after_(&mut self, params: &ExecutorParams) -> ProtocolResult<()> {
Ok(())
}
}
```

feat(framework): add ExecutorParams into hook method

---

binding-macro/tests/mod.rs
built-in-services/asset/src/tests/mod.rs
framework/src/binding/sdk/mod.rs
framework/src/executor/mod.rs
framework/src/executor/tests/service_call_service.rs
protocol/src/traits/binding.rs
protocol/src/types/service_context.rs

feat(framework)
Add `extra: Option<Bytes>` into `ServiceContext`
`Service` call `Service` may need this
Fixes #
```rust
pub struct ServiceContext {
...
extra: Option<Bytes>,
...
}
impl ServiceContext {
pub fn get_extra(&self) -> Option<Bytes> {
self.extra.clone()
}
}
pub trait ServiceSDK {
fn read(
&self,
ctx: &ServiceContext,
extra: Option<Bytes>,
service: &str,
method: &str,
payload: &str,
) -> ProtocolResult<String>;
fn write(
&mut self,
ctx: &ServiceContext,
extra: Option<Bytes>,
service: &str,
method: &str,
payload: &str,
) -> ProtocolResult<String>;
}
```

feat(framework): add extra: Option<Bytes> to ServiceContext

---

framework/src/executor/tests/mod.rs
framework/src/lib.rs

feat
add execute benchmark
Fixes #

feat(muta): bench excute

---

core/api/Cargo.toml
core/api/src/lib.rs
core/api/src/schema/block.rs
core/api/src/schema/mod.rs
core/api/src/schema/receipt.rs
core/api/src/schema/transaction.rs

feat
Juniper now supports async on master
https://github.com/graphql-rust/juniper/issues/2#issuecomment-576805250
Fixes #

feat: Update juniper, supports async

---

core/consensus/src/engine.rs

fix repeat txs problem
Fixes #

fix(muta): flush mempool after storage

---

core/mempool/src/lib.rs

fix(mempool): filter callback_cache while pull txs

---

core/network/src/common.rs
core/network/src/error.rs
core/network/src/message/mod.rs
core/network/src/outbound/rpc.rs
core/network/src/peer_manager/mod.rs
core/network/src/peer_manager/peer.rs
core/network/src/protocols/transmitter.rs
core/network/src/reactor/mod.rs
core/network/src/reactor/router.rs
core/network/src/rpc_map.rs
core/network/src/service.rs
core/network/src/traits.rs

change
- output connected address with rpc timeout and drop error
- output connected peers number when poll peer manager
- delete rpc entry in rpc map after timeout
Fixes #

change(network): output more info for debug rpc timeout

---

core/consensus/src/synchronization.rs

fix
Check the height again after lock to make sure the node doesn't into sync again.
Fixes #

[ᚬdebug-muta] fix(sync): Check the height again after lock

---

core/consensus/src/message.rs
core/mempool/src/adapter/message.rs
core/mempool/src/lib.rs
core/network/examples/buycopy.rs
core/network/src/reactor/mod.rs
core/network/tests/gossip_test.rs
protocol/src/traits/network.rs

Error inside process logic should not be propagated to network.
change
Remove ProtocolResult from message handle signature. Logic error should not
be progagated to network.
Fixes #

[ᚬdebug-muta] change(network): remove ProtocolResult from message handle trait

---

built-in-services/metadata/src/tests/mod.rs
core/consensus/src/adapter.rs
core/consensus/src/engine.rs
core/consensus/src/status.rs
core/consensus/src/synchronization.rs
core/consensus/src/tests/synchronization.rs
core/mempool/src/adapter/mod.rs
core/mempool/src/lib.rs
core/mempool/src/tests/mempool.rs
core/mempool/src/tests/mod.rs
core/mempool/src/tx_cache.rs
devtools/chain/genesis.toml
protocol/src/fixed_codec/primitive.rs
protocol/src/traits/consensus.rs
protocol/src/traits/mempool.rs
protocol/src/types/primitive.rs
src/default_start.rs

New feature.
- Add tx size check to prevent attacking by composing big tx
- Add tx_num_limit to genesis, and it will pack at most this number of tx into a block.
- Change the meaning of cycles_limit in genesis. It becomes the limit of every tx instead of the whole block.
Fixes #

feat: check size and cycle limit when insert tx into mempool

---

core/api/src/config.rs
core/api/src/lib.rs

chore
The configuration field name `maxconn` does not match the role, what it really does is "max conn per worker".
\-
\-

chore(config): the effect of the maxconn field matches its name now

---

framework/src/binding/store/array.rs
framework/src/binding/store/primitive.rs
framework/src/binding/tests/sdk.rs
framework/src/binding/tests/store.rs
protocol/src/traits/binding.rs

fix binding `StoreType`
binding store type should return Option None instead of panic when method get none
Fixes #

fix(binding): store type should return Option None instead of panic

---

core/mempool/src/map.rs
core/mempool/src/tx_cache.rs

Performance
Origin benchmark:
```
test map::tests::bench_map_insert          ... bench:     158,499 ns/iter (+/- 4,657)
```
After remove pre-judgment before insert
```
test map::tests::bench_map_insert          ... bench:     122,443 ns/iter (+/- 4,326)
```
After rewrite `get_index()`
```
test map::tests::bench_map_insert          ... bench:      80,451 ns/iter (+/- 3,151)
```
Fixes #

refactor(mempool): Improve mempool's performance close to 100%

---

framework/src/binding/store/array.rs
framework/src/binding/store/map.rs
framework/src/binding/store/primitive.rs
framework/src/binding/tests/store.rs
protocol/src/traits/binding.rs

bug
fix bug of StoreUint64 overflow panic
Fixes #

fix(binding):overflow of StoreUint64 trait, modify foo_ to inner_foo

---

core/mempool/Cargo.toml
core/mempool/src/lib.rs
core/mempool/src/map.rs
core/mempool/src/tests/mempool.rs
core/mempool/src/tests/mod.rs
core/mempool/src/tx_cache.rs

refactor
Change the concurrent operation based on `rayon` in the transaction pool to `tokio::spawn`. Since `rayon` has its own independent thread pool, it will cause unnecessary contention when used with the tokio runtime.
Fixes #

refactor(mempool): Replace rayon with `tokio::spawn`

---

core/mempool/src/adapter/mod.rs
core/mempool/src/lib.rs
core/mempool/src/tests/mempool.rs

refactor
Verify signatures in parallel using `tokio::spawn` and `tokio::spawn_blocking`
benchmark for 4 threads
```
bench_sign size 30000 cost 12.412875051s
bench_sign_with_spawn_list size 30000 cost 3.584893563s
```
Fixes #

refactor(mempool): Verify signatures in parallel

---

common/apm/Cargo.toml

chore
* upgrade muta-apm version that reports tags and logs when returning error 
Fixes #

chore: upgrade muta-apm version that span error log

---

Cargo.toml
common/apm/src/metrics/mempool.rs
common/apm/src/metrics/network.rs
core/consensus/src/engine.rs
core/network/src/connection/control.rs
core/network/src/outbound/gossip.rs
core/network/src/outbound/rpc.rs
core/network/src/protocols/transmitter.rs
core/network/src/reactor/router.rs
src/default_start.rs

feat
monitor realtime mempool tx count
Fixes #

feat: supported mempool monitor

---

core/consensus/Cargo.toml
core/consensus/src/engine.rs
core/consensus/src/wal.rs

refactor
* ignore path already exists when saving wal
* upgrade overlord version
Fixes #

fix(WAL): Ignore path already exist

---

framework/src/executor/mod.rs
framework/src/executor/tests/mod.rs
framework/src/executor/tests/test_service.rs

fix
Transaction events aren't cleared on execution error. 
Fixes # 18

fix(executor): tx events aren't cleared on execution error

---

common/crypto/Cargo.toml
common/crypto/src/lib.rs
core/consensus/src/adapter.rs
core/consensus/src/tests/synchronization.rs
core/consensus/src/util.rs
protocol/src/traits/consensus.rs

fix
1. Bump ophelia-bls-amcl version from 0.1 to 0.2 which includes an API argument change.
2. Fix verify an aggregated signature in checking proof. The BLS public keys should be recovered from metadata, rather than the current Address-PubKey Map.
Fixes #

fix(proof): Verify aggregated signature in checking proof

---

binding-macro/tests/mod.rs
core/api/src/adapter/mod.rs
core/consensus/src/adapter.rs
core/consensus/src/engine.rs
core/consensus/src/synchronization.rs
core/consensus/src/tests/synchronization.rs
core/consensus/src/util.rs
framework/src/executor/tests/mod.rs
framework/src/executor/tests/service_call_service.rs
protocol/src/traits/consensus.rs
protocol/src/traits/executor.rs

refactor
Add `proposer` field in `ExecutorParams` struct. So that service can get the proposer address when developing after block hook.
Fixes #

refactor(executor): add proposer field in executor params

---

framework/src/executor/mod.rs
framework/src/executor/tests/mod.rs
framework/src/executor/tests/test_service.rs

feat
Right now, tx panic will revert state changes in tx hook. This pr split tx execution into
thress phrases:
- tx hook before
- tx
- tx hook after
All phrases can commit their changes independently.
Fixes #

feat(executor): indenpendent tx hook states commit

---

framework/src/executor/mod.rs
framework/src/executor/tests/mod.rs
framework/src/executor/tests/test_service.rs
protocol/src/types/service_context.rs

feat
Right now, there is not way to cancel a tx execution. This pr provides a way to do
it through ```ServiceContext```.
Execution Flows: ( PR #316 
tx hook before units -----> tx unit -----> tx hook after units
Once canceled, following execution unit will not be executed.
Current execution changes will still be saved. We can still revert
those changes using panic.
Fixes #
Require PR #316

feat(executor): allow cancel execution units through context

---

framework/src/binding/store/array.rs
framework/src/binding/store/map.rs
framework/src/binding/store/mod.rs
framework/src/binding/store/primitive.rs
framework/src/binding/tests/store.rs
protocol/src/traits/binding.rs

refactor
* Change the index type of `DefaultStoreArray` and `DefaultStoreMap` to u64.
* Change the return type of `len()` method to u64.
Fixes #

refactor(store): change index and len to u64

---

framework/src/executor/mod.rs
framework/src/executor/tests/mod.rs

change
Should not panic when service not found in call fn
Fixes #

change(executor): panic when service not found in call fn

---

built-in-services/multi-signature/Cargo.toml
built-in-services/multi-signature/src/lib.rs
built-in-services/multi-signature/src/tests/curd_test.rs
built-in-services/multi-signature/src/tests/mod.rs
built-in-services/multi-signature/src/types.rs

refactor
* Instead of using a global variable, use a local variable to calculate the multi-signature recursion depth.
* remove redundancy signature verify in `add_account`, `remove_account`, `set_threshold` .etc
* refactor check recursion depth function, when the depth is overflow, stop check immediately.
* Add adaptive address. If the owner address in the payload is `0xffffffffffffffffffffffffffffffffffffffff`, use the multi-signature address as the owner address.
Fixes #

refactor(service): calculate multi-signature recursion depth

---

built-in-services/authorization/Cargo.toml
built-in-services/authorization/src/lib.rs
built-in-services/authorization/src/types.rs

refactor
* Change the type of `verified_map` from `StoreMap` to `StoreArray`, so that different methods of the same service can be registered.
* Remove `verify_signature` method is forbidden.
Fixes #

refactor(auth): change verified map to array

---

Makefile
built-in-services/asset/src/lib.rs
core/api/src/schema/receipt.rs
framework/src/binding/tests/sdk.rs
framework/src/executor/tests/service_call_service.rs
framework/src/executor/tests/test_service.rs
jenkins-x-unit.yml
protocol/src/codec/receipt.rs
protocol/src/fixed_codec/tests/mod.rs
protocol/src/types/primitive.rs
protocol/src/types/receipt.rs
protocol/src/types/service_context.rs

BREAKING CHANGE
feature
to enhance event to include one new field:
name : String , this indicates the event name in the context
provided applied, this pr will help client to use 'name' field to filter events they interest, instead of try read JSON data to identify JSON data's type

feat!: add 'name' field in event struct

---

core/storage/src/tests/adapter.rs
core/storage/src/tests/mod.rs
core/storage/src/tests/storage.rs

fix
panic when test batch receipts get
Fixes #

fix(storage): panic when test batch receipts get

---

core/network/src/peer_manager/peer.rs

change
Remove unsafe conversion code between Connectedness and usize
Fixes #

fix(network): remove unsafe conversion between Connectedness and usize

---

core/mempool/src/lib.rs
core/mempool/src/tests/mempool.rs
core/mempool/src/tests/mod.rs

Fix a security issue
The `ensure_order_txs` needs to ensure that there is no duplicate transaction hash in `order_transactions` so that avoid bad nodes that package a block that contains repeated transactions.
Fixes #

fix(mempool): Ensure that there are no duplicate transactions in the order transaction

---

protocol/src/types/primitive.rs

feat: add from_hex() back into Address
Address can be created by Bech32 address format and raw bytes format, it could also be created by HexString as Hex equals to bytes

feat: add from_hex() back into Address

---

core/consensus/src/adapter.rs
core/consensus/src/engine.rs
core/consensus/src/lib.rs
core/consensus/src/util.rs

fixed a potential security problem.
If the timestamp of the proposal is not verified, the bad node will be able to pass an arbitrarily large time, causing a huge fluctuation in the blockchain time.
So, we should limit the proposal's timestamp to two conditions:
1. The previous block timestamp should be less than proposal timestamp.
2. this node timestamp should be longer than the proposal timestamp
Fixes #

fix(consensus): Add timestamp checking

---

benchmark/bench.rs
benchmark/mod.rs

feat
Add a perf benchmark macro to do benchmark when assets exist.
```log
10 assets bench::perf_execute  ... bench: 109,202,563 ns/iter (+/- 6,378,009)
100 assets bench::perf_execute  ... bench: 108,859,512 ns/iter (+/- 2,977,622)
1000 assets bench::perf_execute ... bench: 108,037,404 ns/iter (+/- 4,539,634)
10000 asset bench::perf_execute  ... bench: 100,244,123 ns/iter (+/- 18,935,087)
```
It seems that performance has nothing to do with the number of existing assets.
Fixes #

feat(benchmark): add a perf benchmark macro

---

built-in-services/multi-signature/src/lib.rs
built-in-services/multi-signature/src/tests/curd_test.rs
built-in-services/multi-signature/src/tests/recursion_test.rs
built-in-services/multi-signature/src/types.rs
devtools/chain/genesis.toml
docs/build/gql_api.sh
docs/graphql_api.md
tests/e2e/multisig.ts
tests/e2e/sdk.test.ts

fix(multi-sig)!: change interface and substitute adaptive_address for autonomy
BREAKING CHANGE: the interface is changed and affect on all sdk/clients
due to the bech32 format, the adaptive address is not suitable.
so we add 'autonomy' field.
B.T.W. change the UpdateAccountPayload to make it non-ambigious
B.T.W. change the genesis payload to remove ambiguity.
Docs is here
https://github.com/HuobiGroup/huobi-chain-docs/pull/8
Java sdk:
https://github.com/nervosnetwork/muta-sdk-java/pull/24
> due to 2 different iteration, the pr of java sdk has been merged. This is a exclusion this time
Js sdk:
https://github.com/nervosnetwork/muta-sdk-js/pull/23

fix(MultiSig)!: change interface and substitute adaptive_address for autonomy

---

core/network/src/common.rs
core/network/src/config.rs
core/network/src/connection/control.rs
core/network/src/connection/mod.rs
core/network/src/metrics.rs
core/network/src/peer_manager/mod.rs
core/network/src/peer_manager/session_book.rs
core/network/src/peer_manager/shared.rs
core/network/src/peer_manager/test_manager.rs
core/network/src/reactor/router.rs
core/network/src/selfcheck.rs
core/network/src/test/mock.rs
core/network/src/traits.rs
src/config.rs
src/default_start.rs

feat
Restrict connections from same ip. Add ```same_ip_conn_limit``` to network configuration, default value is 1.
We'll reject new connections from ip which reach connection limit.
[DOC PR](https://github.com/nervosnetwork/muta-docs/pull/38)
Fixes #

feat(network): limit connections from same ip

---

core/network/src/config.rs
core/network/src/error.rs
core/network/src/peer_manager/mod.rs
core/network/src/peer_manager/session_book.rs
core/network/src/peer_manager/test_manager.rs
src/config.rs
src/default_start.rs
tests/trust_metric_all/node/full_node/default_start.rs

feat
Support limit inbound and outbound connections. Add ```inbound_conn_limit``` to network configuration.
```outbound_conn_limit``` will be subtracted ```inbound_conn_limit``` from ```max_connections```.
Note:
Base on #388 
[DOC PR](https://github.com/nervosnetwork/muta-docs/pull/39)
Fixes #

feat(network): limit inbound and outbound connections

---

common/apm/src/metrics/consensus.rs
core/consensus/src/synchronization.rs

feat
Each successful download of 50 blocks will complete synchronization to avoid downloading too many blocks from a single node, which will affect the success rate of network transmission.
Fixes #

feat(sync): Limit the maximum height of once sync

---

protocol/src/types/primitive.rs
src/default_start.rs

fix: load hrp before deserializing genesis payload to take hrp effect
N/A
N/A
This is an internal bug and fix doesn't take any changes to toolchains and docs.
hrp should load firstly before deserializing genesis cause Address maybe in service genesis payload may need hrp

fix: load hrp before deserializing genesis payload to take hrp effect

---

benchmark/mod.rs
devtools/chain/config.toml
examples/config-1.toml
examples/config-2.toml
examples/config-3.toml
examples/config-4.toml
framework/Cargo.toml
framework/src/binding/state/trie_db.rs
framework/src/binding/tests/state.rs
src/config.rs
src/default_start.rs

Implement an approximately fixed size cache through HashMap. It caches the data used in the latest block, and it will be flushed when committing a block. The size of the cache is 2000, however, this does not mean that it can only store 2000 data. When the data in the cache is more than 2000 when the cache is refreshed, it will be randomly deleted to 2000. The random seed is the largest prime number within 50000, 49999.
Fixes #
Ref https://github.com/nervosnetwork/muta-docs/pull/55

perf(state): add state cache for trieDB

---

built-in-services/asset/src/lib.rs
built-in-services/authorization/src/lib.rs
built-in-services/metadata/src/lib.rs
built-in-services/multi-signature/src/lib.rs
built-in-services/util/src/lib.rs
examples/muta-chain.rs
framework/src/executor/tests/framework.rs
framework/src/executor/tests/mod.rs
framework/src/executor/tests/test_service.rs
protocol/src/types/service_context.rs

fix: service field of event is not binded to ctx.service
the service field of event was binded to ctx.event.
now it is free to set, in order to indicate which service emits the give events
Ref #  n/a, this is an internal fix
toolchain change N/A.
Breaking Change

fix!: service field of event is not binded to ctx.service

---

benchmark/governance/mod.rs
built-in-services/asset/src/lib.rs
built-in-services/metadata/src/lib.rs
built-in-services/multi-signature/src/lib.rs
protocol/src/traits/binding.rs

refactor
* Change service interface return type from `Result<T, ServiceResponse<()>>` to `ServiceResponse<T>`.
* Add a `try_service_response` macro for handling service response.
e.g.
```rust
/// Expand code
/// let balance = {
///     if resp.is_error() {
///         return ServiceResponse::from_error(resp.code, resp.error_message);     
///     }
///     resp.succeed_data
/// };
let resp = asset.balance_(ctx, payload);
let balance = try_service_response!(resp);
```
The corresponding doc PR is https://github.com/nervosnetwork/muta-docs/pull/36/files
Fixes #

refactor(service): change service interface return type

---

built-in-services/multi-signature/src/lib.rs
built-in-services/multi-signature/src/tests/curd_test.rs

1. Refactor the `decode_list` method in multi-signature service. Avoid using `expect`.
2. Refactor the `ServiceError` return.
docs: N/A
toolchain: N/A

refactor(service): change the rlp decode list

---

core/network/src/connection/keeper.rs
core/network/src/event.rs
core/network/src/peer_manager/mod.rs

Right now, we will give up a peer after secio handshake timeout. This PR handle this timeout error, instead
of give up peer, we just increase its address failure count, so that we can try this peer again.
Fixes #
Ref #

fix(network): give up peer because of handshake timeout

---

core/network/src/peer_manager/mod.rs

Add warn log before give up peer
Fixes #
Ref #

fix(network): give up a peer without log a reason

---

Cargo.toml
core/consensus/Cargo.toml
core/consensus/src/engine.rs
core/consensus/src/lib.rs
core/consensus/src/wal.rs
core/mempool/src/lib.rs
core/mempool/src/tests/mempool.rs
core/mempool/src/tests/mod.rs
protocol/Cargo.toml
protocol/src/traits/mempool.rs
src/default_start.rs
tests/common/node/full_node/default_start.rs

1. Fix a bug that may cause inactivation. Recover signed transactions from wal when reboot. Then insert them to the mempool.
2. Add a check of the ordered transaction hash when commit.
3. Upgrade overlord version.
Fixes #
Ref #

fix(consensus): recover and insert tx to mempool to avoid inactivation

---

core/network/src/peer_manager/mod.rs

Unconnectable peers will be filtered out when peer managers try to connect a list of peers.
This PR change this behaviour, so that consensus peers can be tried again.
Fixes #
Ref #

feat(network): retry unconnectable consensus peer

---

core/network/src/connection/keeper.rs

When a peer connection result in secio io error, this peer will be marked
as unconnectable. We will not try to connect to this peer in the future.
In this PR, we treat secio io error as normal io error, don't mark this peer
as unconnectable. 
Fixes #
Ref #

fix(network): give up peer due to secio io error

---

core/network/src/peer_manager/mod.rs

Use collection's length directly, this should fix negative connecting number gauge now.
Fixes #
Ref #

fix(network): negative connecting metric number

---

common/logger/Cargo.toml
common/logger/src/date_fixed_roller.rs
common/logger/src/lib.rs
devtools/chain/config.toml
src/config.rs
src/lib.rs
tests/trust_metric_all/logger.rs

This PR add ```file_size_limit``` to ```logger``` config. When log file reaches given file size limit, current log
file will be "archived" into ```[data].muta.[timestamp].log```.
Fixes #
Ref #
https://github.com/nervosnetwork/muta-docs/pull/62

feat(logger): split log file by size

---

common/apm/src/metrics.rs
common/apm/src/metrics/network.rs
core/network/src/protocols/ping/behaviour.rs

To better calculate peer ping p90, change ping metric from gauge vec to histogram vec.
In this PR, we set up 5 buckets, [100, 300, 500, 700, 900].
Fixes #
Ref #

feat(network): ping metric from gauge vec to histogram vec

---

framework/src/executor/mod.rs

fix: fix framework to deal with state while tx runs fail
The state should be revert_cache to the previous point(just after tx hook before) while tx body runs fail.
Ref # N/A
No toolchain and docs affected

fix: fix framework to deal with state while tx runs fail

---

core/network/src/protocols/identify/identification.rs

Status lock may still be hold when we wake up identification wait futures.
Fixes #
Ref #

fix(network): identify protocol: possible dead lock in identification

---

core/consensus/Cargo.toml
core/consensus/src/engine.rs

Overlord view change reason adapts to structure log.
Fixes #
Ref #

refactor(consensus): view change reason adapts to structure log

---

framework/src/binding/state/mod.rs

If the value is an empty byte it needs to be returned `null` to keep the behavior consistent with the MPT.
Fixes #
Ref #

fix(state): If value is an empty byte it needs to return none

---

common/apm/src/metrics/network.rs
core/network/src/outbound/gossip.rs
core/network/src/outbound/rpc.rs
core/network/src/protocols/transmitter/behaviour.rs
core/network/src/protocols/transmitter/message.rs
core/network/src/reactor/router.rs
core/network/src/traits.rs

This PR add new network metric: accumulated message size by direction and url(endpoint).
Fixes #
Ref #

feat(metric): add accumulated network message size count

---

core/network/src/peer_manager/shared.rs
core/network/src/protocols/transmitter/behaviour.rs
core/network/src/traits.rs

Fix metric wrong url data size when broadcast to all sessions.
Fixes #
Ref #

fix(metric): network broadcast all data size

---

core/network/src/peer_manager/mod.rs
core/network/src/peer_manager/test_manager.rs

This PR fix wrong connected consensus peer counter. 
When a session closed, we'll try to fetch this session info and use that session
info ```session.peer``` to check whether closed peer is consensus peer or not.
If session is not found, we simply return.
In this PR, we also try use peer id to fetch peer info if session not found.
Fixes #
Ref #

fix(network): wrong connected consensus peer count

---

framework/src/binding/store/array.rs
framework/src/binding/store/map.rs

The `inner_get()` function of `DefaultStoreArray` and `DefaultStoreMap`  return `Ok(None)` when get nothing.
Fixes #
Ref #

refactor: return Ok(None) when get none

---

common/logger/Cargo.toml
common/logger/README.md
common/logger/src/lib.rs
core/consensus/src/engine.rs

Add a json macro to generate json object.
example:
```rust
let json_obj = json!({
"key_01", value_01;
"key_02", value_02
});
```
Fixes #
Ref #

feat(logger): add a json macro to generate json object

---

core/cli/src/lib.rs
core/cli/src/tests/mod.rs
examples/muta-chain.rs
src/lib.rs

fix(cli): expose version, author and app_name to be customized
The author,version and app_name of cli should support customizing.

fix(cli): expose version, author and app_name to be customized

---

core/network/Cargo.toml
core/network/src/peer_manager/mod.rs
core/network/src/peer_manager/test_manager.rs
core/network/src/protocols/identify.rs
core/network/src/protocols/identify/protocol.rs

Fix peer connecting hang due to inconsistent peer state by unchecked unidentified peer session.
New identify protocol introduces unidentified session to peer manager, we have to do addition checks for these
sessions in ```SessionClosed```, ```ConnectFailed``` and ```RepeatedSession``` events to make sure that related
peers have correct state. 
When ```SessionClosed```, ban that peer a random short time, so these peers dont connect to each other simultaneously (note: this wont' effect consensus peer).
Also add new hardcode timeout to outbound connecting and unidentified sessions in peer manager to ensure that
peer connecting will fail within reasonable time in peer manager side.
Also bump tentacle to latest master. …

fix(network): connecting hang
