nervosnetwork/muta

core/consensus/src/engine.rs, core/executor/src/lib.rs
=> feat(consensus): Execute the transactions on commit.

README.md
feature
* add how to compile and run in README
Fixes #
=> feat: add compile and run in README

Cargo.lock, Cargo.toml, devtools/keypair/Cargo.toml, devtools/keypair/src/main.rs
chore
generate peer keypairs
Fixes #
=> chore: move keypair generator into devtools

Cargo.lock, core/api/Cargo.toml, core/consensus/Cargo.toml, core/mempool/Cargo.toml, core/network/Cargo.toml, core/storage/Cargo.toml, protocol/Cargo.toml
=> chore: Update futures crate.

Cargo.lock, common/merkle/Cargo.toml, common/merkle/src/lib.rs
feature
* feat: develop merkle root process
Fixes #
=> feat: develop merkle root

core/mempool/src/map.rs, core/mempool/src/tests/mempool.rs, core/mempool/src/tx_cache.rs
=> fix(mempool): Resize the queue to ensure correct switching.

core/mempool/src/map.rs, core/mempool/src/tx_cache.rs
=> fix(mempool): Fix concurrent insert bug of mempool

README.md, src/main.rs
=> refactor(main): Remove the init subcommand, which is now the default behavior.

core/network/src/common.rs, core/network/src/peer_manager/mod.rs, core/network/src/peer_manager/peer.rs
feat
interval log connected peers and their ips
Fixes #
=> feat(network): log connected peer ips

core/network/src/peer_manager/mod.rs
Don't use if-let
fix
fix network dead lock
Fixes #
=> fix(network): dead lock in peer manager

core/mempool/src/adapter/mod.rs, core/mempool/src/lib.rs, core/mempool/src/tests/mempool.rs, core/mempool/src/tests/mod.rs, protocol/src/traits/mempool.rs, src/main.rs
=> fix(mempool): Always get the latest epoch id when `package`.

src/main.rs
bugfix
fix broadcast new transactions
Fixes #
=> fix(mempool): broadcast new transactions

Cargo.lock, common/merkle/Cargo.toml, core/consensus/Cargo.toml
=> chore: change overlord dependency to rev

Cargo.lock, core/mempool/Cargo.toml, core/mempool/src/adapter/message.rs, core/mempool/src/adapter/mod.rs, core/mempool/src/lib.rs, core/mempool/src/tests/mod.rs, devtools/chain/config.toml, src/config.rs, src/main.rs
feat
Cache batch of signed transactions until we reach specified size or interval, then broadcast them
in one network message.
Fixes #
=> feat(mempool): implement cached batch txs broadcast

CONTRIBUTING.md, README.md, SECURITY.md
chore(doc)
add CONTRIBUTING.md
Fixes #
=> chore(doc): add CONTRIBUTING.md

Cargo.lock, core/consensus/Cargo.toml, core/consensus/src/adapter.rs, core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/fixed_types.rs, core/consensus/src/lib.rs, core/consensus/src/message.rs, src/main.rs
refactor
change rlp to fixed codec in consensus module
Fixes #
=> refactor(consensus): change rlp to fixed codec

.github/CODEOWNERS, Cargo.toml, LICENSE, common/channel/Cargo.toml, common/config-parser/Cargo.toml, common/crypto/Cargo.toml, common/logger/Cargo.toml, common/merkle/Cargo.toml, common/metrics/Cargo.toml, common/pubsub/Cargo.toml, core/api/Cargo.toml, core/consensus/Cargo.toml, core/executor/Cargo.toml, core/mempool/Cargo.toml, core/network/Cargo.toml, core/storage/Cargo.toml, protocol/Cargo.toml, src/main.rs
=> chore: change contact from cryptape to nervos

Cargo.lock, core/api/src/lib.rs, core/consensus/Cargo.toml
feat(api)
- support CORS
- hiding errors detail like AccountNotFound when fetching balance
Fixes #
=> feat(api): make API more user-friendly

Cargo.lock, core/consensus/Cargo.toml
=> chore: update overlord

Cargo.lock, common/crypto/Cargo.toml, core/network/examples/buycopy.rs, core/network/src/config.rs, core/network/tests/common.rs
=> chore: Update all crates.

protocol/src/codec/transaction.rs, protocol/src/fixed_codec/tests/mod.rs, protocol/src/fixed_codec/transaction.rs, protocol/src/types/transaction.rs
feat
Add cycles_price for raw_transaction.
Fixes #
- protocol/src/types/transaction.rs
=> [ᚬframework] feat(protocol/types): Add cycles_price for raw_transaction.

Cargo.lock, Cargo.toml, core/binding-macro/Cargo.toml, core/binding-macro/src/lib.rs, core/binding/Cargo.toml, core/binding/src/lib.rs, protocol/src/fixed_codec/epoch.rs, protocol/src/fixed_codec/genesis.rs, protocol/src/fixed_codec/macro.rs, protocol/src/fixed_codec/mod.rs, protocol/src/fixed_codec/primitive.rs, protocol/src/fixed_codec/receipt.rs, protocol/src/fixed_codec/tests/fixed_codec.rs, protocol/src/fixed_codec/transaction.rs, protocol/src/traits/binding.rs, protocol/src/traits/consensus.rs, protocol/src/traits/executor.rs, protocol/src/traits/mod.rs
feat
**Binding**: provides the application layer (Riscv Runtime) with access to the blockchain and allows Rust developers to write build-in services
Fixes #
protocol/src/traits/binding.rs
=> [ᚬframework] feat(protocol/traits): Add traits of binding.

core/binding-macro/src/common.rs, core/binding-macro/src/cycles.rs, core/binding-macro/src/lib.rs, core/binding-macro/src/read_write.rs, core/binding-macro/tests/mod.rs
featrue
Automatically generate code that consumes the specified cycles.
```rust
// Source Code
#[cycles(200)]
fn test_sub_cycles_fn<Context: RequestContext>(ctx: Context) -> ProtocolResult<()> {
Ok(())
}
// Generated code.
fn test_sub_cycles_fn<Context: RequestContext>(ctx: Context) -> ProtocolResult<()> {
ctx.sub_cycles(200)?;
Ok(())
}
```
Fixes #
=> [ᚬframework] feat(core/binding-macro): Add cycles proc-marco.

Cargo.lock, core/consensus/Cargo.toml, core/consensus/src/lib.rs, core/consensus/src/trace.rs, src/main.rs
feature
The consensus algorithm always plays with a distributed system, debugging or optimizing is so hard. If we can record events to describe what happen when consensus state changes, and then replay with a visualization dashboard, the debugging or optimizing would be easier.
Fixes #
=> feat: support consensus tracing

.travis.yml
chore
Reduce travis cache size
Fixes #
=> chore(ci): reduce travis cache size

.travis.yml, devtools/ci/install.sh, devtools/ci/script.sh
Try fix cahce timeout
chore
Fix travis cache timeout again :)
Use sccache and limit its cache size to 2G.
Fixes #
=> chore(ci): use sccache and limit its cache size to 2G

.travis.yml
chore
Disable sccache on master since master hasn't installed it yet.
Will enable it in another PR.
Fixes #
=> chore(ci): disable sccache on master

.travis.yml
chore
Enable sccache, master should have sccache installed now.
Fixes #
=> chore(ci): enable sccache

core/binding-macro/src/lib.rs, core/binding-macro/src/servive.rs, core/binding-macro/tests/mod.rs, protocol/src/traits/binding.rs
Feature
Methods marked `#[init]` will be used to initialize the service.
Fixes #
=> [ᚬframework] feat(core/binding-macro): Add #[init] attribute.

devtools/ci/install.sh
fix
Fix sccache installation on rust-toolchain change
Fixes #
=> fix(ci): fail to install sccache after new rust-toolchain

Cargo.lock, Cargo.toml, core/api/Cargo.toml, core/api/src/adapter/mod.rs, core/api/src/lib.rs, core/api/src/schema/epoch.rs, core/api/src/schema/mod.rs, core/api/src/schema/receipt.rs, core/api/src/schema/transaction.rs, core/consensus/src/util.rs, devtools/chain/genesis.toml, devtools/chain/genesis.yaml, framework/src/executor/tests/genesis_services.toml, protocol/Cargo.toml, protocol/src/lib.rs, protocol/src/traits/api.rs, protocol/src/traits/binding.rs, src/main.rs
feature
The following interfaces have been added and modified.
- getEpoch
- getTransaction
- getReceipt
- sendTransaction
- unsafeSendTransaction
- queryService
You can try to access graphiql in your browser.
```sh
cd muta && cargo run
oepn http://localhost:8000/graphiql
```
Fixes #
See `core/api/src/lib.rs` for API definition and logic.
See `core/api/src/schema/*.rs` for API data structure.
=> [ᚬframework] feat(graphql): Modify the GraphQL API to fit the framework data structure.

devtools/keypair/src/main.rs
bug fix
https://github.com/nervosnetwork/muta/blob/c4a379fe36f21b27cdd83a8289c75e855364e755/src/default_start.rs#L237 Expect a hex string.
Fixes #
=> [ᚬmaster] fix(keypair):  Hex encoding common_ref.

Cargo.toml, binding-macro/Cargo.toml, built-in-services/asset/Cargo.toml, common/channel/Cargo.toml, common/config-parser/Cargo.toml, common/crypto/Cargo.toml, common/logger/Cargo.toml, common/merkle/Cargo.toml, common/metrics/Cargo.toml, common/pubsub/Cargo.toml, core/api/Cargo.toml, core/consensus/Cargo.toml, core/mempool/Cargo.toml, core/network/Cargo.toml, core/storage/Cargo.toml, devtools/keypair/Cargo.toml, framework/Cargo.toml, protocol/Cargo.toml
chore
- Update version to 0.1.0-alpha.0
- Rename protocol to muta-protocol
Fixes #
=> [ᚬmaster] chore: Update the version in Cargo.toml.

core/api/src/adapter/mod.rs, core/api/src/lib.rs, core/api/src/schema/transaction.rs, core/consensus/src/adapter.rs, framework/src/executor/mod.rs, framework/src/executor/tests/mod.rs, framework/src/executor/tests/service_call_service.rs, protocol/src/traits/api.rs, protocol/src/traits/executor.rs
fix
Fixes #
fix hex decode failed
@yejiayu
=> [ᚬmaster] fix: fix hex decode failed

examples/muta-chain.rs
feature
example:
```bash
$ CONFIG=examples/chain0.toml GENESIS=examples/genesis.toml cargo run --release --example muta-chain
```
default CONFIG: `devtools/chain/config.toml`
default GENESIS: `devtools/chain/genesis.toml`
Fixes #
=> [ᚬmaster] feat(example): Support for passing dynamic config through the ENV

core/consensus/Cargo.toml, core/consensus/src/engine.rs, core/consensus/src/status.rs, core/consensus/src/synchronization.rs, core/consensus/src/util.rs, devtools/chain/config.toml, src/config.rs, src/default_start.rs
feature
* add moodyblus trace in consensus module
* let bls private key extended from secp256k1 private key 
Fixes #
=> [ᚬmaster] feat(trace): add moodyblue trace

core/api/src/schema/schema.graphql
Add schema.graphql to the repo.
This schema file can be a reference for sdk developers.
Fixes #
=> [ᚬmaster] feat: add api schema

framework/src/executor/mod.rs
bug fix
Any errors that transaction execution should be written to the `Receipt.response`.
Fixes #
=> [ᚬmaster] fix(framework/executor): Catch any errors in the call

core/consensus/src/adapter.rs, core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/status.rs, src/default_start.rs
refactor
I don't quite understand why the previous code shared the `CurrentConsensusStatus` using both the channel and the read-write lock, which is too weird.
After refactoring, the`CurrentConsensusStatus` will use the read-write lock sharing uniformly.
Fixes #
=> [ᚬmaster] refactor(consensus): Use RwLock to share consensus status.

core/consensus/Cargo.toml
fix
Overlord not found on github!
Fixes #
@KaoImin 
@yejiayu
=> [ᚬmaster] fix: fix overlord not found error

devtools/keypair/Cargo.toml
chore
update muta-keypair version
Fixes #
=> [ᚬmaster] chore: udate muta-keypair version for publish

core/consensus/src/adapter.rs, core/consensus/src/status.rs, core/consensus/src/synchronization.rs
=> [ᚬmaster] chore(log): make log info pretty

README.md
=> [ᚬmaster] chore(doc): update README

protocol/src/codec/mod.rs
chore
implement ProtocolCodec for Bytes
Fixes #
=> chore(protocol): implement ProtocolCodecSync for Bytes

core/api/src/adapter/mod.rs, core/consensus/Cargo.toml, core/consensus/src/engine.rs, core/consensus/src/fixed_types.rs, core/storage/src/tests/mod.rs, devtools/chain/config.toml, framework/src/binding/tests/sdk.rs, protocol/src/codec/epoch.rs, protocol/src/fixed_codec/epoch.rs, protocol/src/fixed_codec/tests/mod.rs, protocol/src/types/epoch.rs, src/default_start.rs
return receipt until epoch executed
Fixes #
@zeroqn 
@yejiayu
=> [ᚬmaster] feat: return receipt until epoch executed

core/consensus/Cargo.toml, core/consensus/src/status.rs
bugfix
* fix check state roots may cause consensus immutable
* update overlord github commit hash
Fixes #
=> fix(consensus): fix check state roots

built-in-services/asset/src/lib.rs, built-in-services/asset/src/types.rs, devtools/chain/genesis.toml
=> chore: Update genesis

core/network/Cargo.toml, core/network/src/message/mod.rs, protocol/Cargo.toml, protocol/src/codec/epoch.rs, protocol/src/codec/mod.rs, protocol/src/codec/primitive.rs, protocol/src/codec/receipt.rs, protocol/src/codec/transaction.rs
=> chore: Update prost to v0.6

devtools/keypair/Cargo.toml, protocol/Cargo.toml
=> chore: Update muta protocol

built-in-services/asset/src/tests/mod.rs, core/consensus/Cargo.toml, core/consensus/src/adapter.rs, core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/lib.rs, core/consensus/src/status.rs, core/consensus/src/util.rs, core/network/src/traits.rs, core/storage/src/adapter/rocks.rs, core/storage/src/lib.rs, core/storage/src/tests/storage.rs, examples/muta-chain.rs, framework/src/binding/tests/sdk.rs, framework/src/executor/tests/mod.rs, protocol/Cargo.toml, protocol/src/codec/tests/mod.rs, protocol/src/codec/transaction.rs, protocol/src/fixed_codec/tests/mod.rs, protocol/src/traits/consensus.rs, protocol/src/traits/storage.rs, protocol/src/types/epoch.rs, protocol/src/types/mod.rs, protocol/src/types/transaction.rs, src/default_start.rs
feature
* develop muta consensus wal
Fixes #
=> [ᚬtest-chain] feat(wal): develop muta consensus wal

core/network/src/error.rs, core/network/src/outbound/rpc.rs
fix
default rpc timeout to 4 seconds
Fixes #
=> fix(network): default rpc timeout to 4 seconds

built-in-services/riscv/src/tests/duktape.rs, built-in-services/riscv/src/tests/test_code.js, built-in-services/riscv/src/vm/c/duktape_ee.c, built-in-services/riscv/src/vm/c/duktape_ee_helper.h
feat
Complete duktape syscall support
Fixes #
=> [ᚬriscv] Complete duktape ee

built-in-services/riscv/src/tests/test_code.js, built-in-services/riscv/src/vm/c/duktape_ee.c
feat
duktape now allow multiple functions
Fixes #
=> [ᚬriscv] [riscv] duktape allow multiple functions

framework/src/executor/mod.rs
fix bug
Logic to deal with hook is wrong: if service call another service in hook method, the modified state of another service would not be committed,  which is not correct.
Fixes #
=> fix(executor): wrong hook logic

core/storage/Cargo.toml, core/storage/src/lib.rs
perf
Cache latest epoch
Fixes #
=> perf(storage): cache latest epoch

core/network/src/config.rs, core/network/src/outbound/rpc.rs, core/network/src/service.rs, devtools/chain/config.toml, src/config.rs, src/default_start.rs
chore
configure rpc timeout through file
Fixes #
=> chore(network): configure rpc timeout through file

Cargo.toml, core/consensus/Cargo.toml, core/consensus/src/engine.rs, core/consensus/src/fixed_types.rs, core/mempool/Cargo.toml, core/mempool/src/adapter/message.rs, core/mempool/src/adapter/mod.rs, core/mempool/src/lib.rs, core/network/Cargo.toml, core/network/examples/buycopy.rs, core/network/src/connection/control.rs, core/network/src/connection/mod.rs, core/network/src/error.rs, core/network/src/event.rs, core/network/src/peer_manager/mod.rs, core/network/src/protocols/core.rs, core/network/src/protocols/discovery.rs, core/network/src/protocols/identify.rs, core/network/src/protocols/ping.rs, core/network/src/reactor/mod.rs, core/network/src/reactor/router.rs, core/network/src/service.rs, core/network/src/traits.rs, core/network/tests/common.rs, core/network/tests/gossip_test.rs, examples/muta-chain.rs, src/default_start.rs
refactor
change runtime into tokio
Fixes #
=> refactor: change runtime into tokio

Cargo.toml, built-in-services/metadata/Cargo.toml, built-in-services/metadata/src/lib.rs, built-in-services/metadata/src/tests/mod.rs, protocol/src/fixed_codec/primitive.rs, protocol/src/types/mod.rs, protocol/src/types/primitive.rs
feature
modify metadata structure and add metadata service with test
Fixes #
=> feat: Metadata service

core/consensus/src/synchronization.rs, core/consensus/src/tests/synchronization.rs
feat
Before the synchronization starts, it will wait for the consensus execution queue to end to avoid panic by repeated execution.
Fixes #
=> feat(sync): Wait for the execution queue.

Dockerfile, Makefile
=> chore: Update makefile

built-in-services/asset/src/lib.rs, built-in-services/asset/src/tests/mod.rs, built-in-services/asset/src/types.rs, framework/src/executor/tests/service_call_service.rs
feat(service)
upgrade built-in asset service
Fixes #
=> [ᚬhuobi] feat(service): upgrade built-in asset service

core/consensus/src/adapter.rs, core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/status.rs, core/consensus/src/synchronization.rs, core/consensus/src/tests/synchronization.rs, core/mempool/src/lib.rs, devtools/chain/config.toml, framework/src/binding/tests/sdk.rs, protocol/src/codec/block.rs, protocol/src/fixed_codec/tests/mod.rs, protocol/src/traits/consensus.rs, protocol/src/traits/mempool.rs, protocol/src/types/block.rs, src/config.rs, src/default_start.rs
feat
1. flush metadata while commit 
2. remove repeat params in config.toml
3. uniform validator type
Fixes #
=> feat(muta): flush metadata while commit 

core/api/src/schema/block.rs
feat
Add the exec_height field to the block
Fixes #
=> feat(api): Add the exec_height field to the block

core/consensus/Cargo.toml, core/consensus/src/adapter.rs, core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/status.rs, core/consensus/src/synchronization.rs, core/consensus/src/tests/synchronization.rs, protocol/src/traits/consensus.rs, src/default_start.rs
feat
adapte overlord-0.2.0-alpha.3
Fixes #
=> feat(muta): adapt overlord-0.2.0-alpha.3

core/consensus/Cargo.toml, core/consensus/src/status.rs, core/mempool/Cargo.toml, core/storage/Cargo.toml
bugfix
fix state root in consensus cache can not be clear
Fixes #
=> fix(consensus): state root can not be clear

built-in-services/asset/src/lib.rs, built-in-services/asset/src/tests/mod.rs, built-in-services/asset/src/types.rs, framework/src/executor/tests/mod.rs
fix asset service
adjust two query payloads: GetBalancePayload and GetAllowancePayload
after adjusted
```rust
pub struct GetBalancePayload {
pub asset_id: Hash,
pub user:     Address,
}
pub struct GetAllowancePayload {
pub asset_id: Hash,
pub grantor:  Address,
pub grantee:  Address,
}
```
Fixes #
=> [ᚬhuobi] fix(asset-service): adjust service query payload

core/network/Cargo.toml, core/network/examples/buycopy.rs, core/network/src/common.rs, core/network/src/config.rs, core/network/src/error.rs, core/network/src/peer_manager/disc.rs, core/network/src/peer_manager/mod.rs, core/network/src/peer_manager/peer.rs, core/network/tests/common.rs, src/config.rs, src/default_start.rs
feat
support dns bootstrap
Fixes #
=> [feat] support dns bootstrap

Makefile
fix
Make sure the `make docker-push` command works
Fixes #
=> fix(makefile): Docker push to the correct image

built-in-services/metadata/src/lib.rs, built-in-services/metadata/src/tests/mod.rs, built-in-services/metadata/src/types.rs, devtools/chain/genesis.toml
feat service
upgrade metadata service to manage node
Fixes #
=> [ᚬhuobi] feat(service): upgrade metadata service to manage node

built-in-services/riscv/src/vm/c/pvm.h, built-in-services/riscv/src/vm/interpreter.rs, built-in-services/riscv/src/vm/mod.rs, built-in-services/riscv/src/vm/syscall/assert.rs, built-in-services/riscv/src/vm/syscall/convention.rs, built-in-services/riscv/src/vm/syscall/mod.rs
feat
add assert syscall
Fixes #
=> [ᚬhuobi] feat(riscv): add assert syscall

core/network/src/connection/keeper.rs, core/network/src/event.rs, core/network/src/peer_manager/mod.rs
fix
fix network give up retry
Fixes #
=> fix(network): give up retry

docs/build/gql_api.sh, docs/graphql_api.md
fix
fix the href link inside graphql_api.md which is auto gened by gql_api.sh by target 'doc api ' in makefile
N/A
Fixes #
=> fix(doc): fix graphql_api doc link and doc-api build sh

core/consensus/src/synchronization.rs
=> fix(sync): Flush the memory pool when the storage success

core/network/src/outbound/rpc.rs
fix
fix rpc memory leak if rpc call future is dropped
Fixes #
=> fix(network): rpc memory leak if rpc call future is dropped

core/consensus/src/engine.rs
bugfix
If the block is proposed by self, do not synchronize txs.
Fixes #
=> fix(consensus): sync txs context no session id

core/consensus/src/synchronization.rs
feat
If the node is only 1 height behind, wait for a period of time (equals consensus interval) first, and enter synchronization if it is still 1 height behind.
Fixes #
=> feat(sync): Trigger sync after waiting for consensus interval

core/consensus/src/engine.rs
bugfix
Check logs bloom when overlord check block.
Fixes #
=> fix(consensus): check logs bloom when check block

core/mempool/src/lib.rs
=> [ᚬdebug-muta] fix(mempool): add infos for debug in mempool

core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/message.rs, core/consensus/src/synchronization.rs
=> [ᚬdebug-muta] chore(sync): Add debug logs

core/network/src/protocols/transmitter.rs
change
remove old bytes migration code
Fixes #
=> [ᚬdebug-muta] change(network): remove useless bytes 0.4 to 0.5 migration code

core/network/src/peer_manager/mod.rs, core/network/src/peer_manager/peer.rs
change
reduce retry interval
Fixes #
=> [ᚬdebug-muta] change(network): reduce retry interval

core/consensus/src/synchronization.rs
refactor
Lock-on entering synchronization to prevent unnecessary network messages and ensure that only one request is accepted.
Fixes #
=> [ᚬdebug-muta] refactor(sync): Ensure that only need_sync is triggered at the s ame time

core/mempool/src/lib.rs
=> [ᚬdebug-muta] fix(mempool): search storage in sync propose tx

core/mempool/src/lib.rs
fix
mempool sync proposal txs
Fixes #
=> [ᚬdebug-muta] fix(mempool): sync proposal txs doesn't insert txs at all

core/network/src/config.rs, core/network/src/connection/mod.rs, core/network/src/lib.rs, core/network/src/peer_manager/mod.rs, core/network/src/peer_manager/peer.rs, core/network/src/reactor/router.rs, core/network/src/selfcheck.rs, core/network/src/service.rs, core/network/src/traits.rs, devtools/chain/config.toml, src/config.rs, src/default_start.rs
feat
- interval report pending data size
- expose yamux config
Fixes #
=> feat(network): interval report pending data size

built-in-services/asset/src/lib.rs, built-in-services/asset/src/tests/mod.rs, built-in-services/asset/src/types.rs, framework/src/executor/tests/mod.rs, framework/src/executor/tests/service_call_service.rs
feat:service
upgrade asset service to test bench
Fixes #
=> [ᚬdebug-muta] feat(service): Upgrade asset

built-in-services/asset/src/lib.rs, built-in-services/asset/src/tests/mod.rs, built-in-services/asset/src/types.rs, framework/src/executor/tests/mod.rs, framework/src/executor/tests/service_call_service.rs
Reverts nervosnetwork/muta#181
=> Revert "[ᚬdebug-muta] feat(service): Upgrade asset"

built-in-services/metadata/src/tests/mod.rs, core/consensus/Cargo.toml, core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/status.rs, core/consensus/src/tests/synchronization.rs, core/consensus/src/util.rs, devtools/chain/config.toml, devtools/chain/genesis.toml, protocol/src/fixed_codec/primitive.rs, protocol/src/types/mod.rs, protocol/src/types/primitive.rs, src/config.rs, src/default_start.rs
feat: adjust bls_pub_key config
move bls_pub_key config to genesis.toml, so we can update validator through service
Fixes #
=> feat(config): move bls_pub_key config to genesis.toml

core/consensus/Cargo.toml
=> chore: Update overlord to 0.2.0-alpha.6

core/consensus/Cargo.toml
=> chore: Update overlord to 0.2.0-alpha.7

core/api/src/schema/block.rs
update api
add hash field to api(get_block) response
Fixes #
```rust
// new get_block response
pub struct Block {
#[graphql(description = "The header section of a block")]
header:            BlockHeader,
#[graphql(description = "The body section of a block")]
ordered_tx_hashes: Vec<Hash>,
#[graphql(description = "Hash of the block")]
hash:              Hash,
}
```
- Already passed test in graphiql
=> api: update get_block 

core/consensus/Cargo.toml, core/consensus/src/engine.rs
* fix recover block hash from bytes when saving full transactions
* update overlord version which fixes three nodes may stuck
Fixes #
=> fix(consensus): block hash from bytes

core/mempool/Cargo.toml, core/mempool/src/lib.rs, core/mempool/src/tests/mempool.rs, core/mempool/src/tx_cache.rs
fix
1. add a RwLock to avoid inserting tx during flush_memory
2. flush incumbent queue in each flush operation
3. fix insert propose tx
Fixes #
=> fix(mempool): fix repeat txs, add flush_incumbent_queue

built-in-services/asset/src/lib.rs, built-in-services/asset/src/tests/mod.rs, built-in-services/asset/src/types.rs, framework/src/executor/tests/mod.rs, framework/src/executor/tests/service_call_service.rs
feat service
upgrade asset service
Fixes #
=> feat(service): upgrade asset service

core/network/src/peer_manager/mod.rs
change
enforce max connection config, drop new connection
Fixes #
=> change(network): enforce max connection config, drop new conection

built-in-services/asset/src/tests/mod.rs, built-in-services/metadata/src/tests/mod.rs, core/consensus/Cargo.toml, core/consensus/src/adapter.rs, core/consensus/src/engine.rs, core/storage/src/lib.rs, framework/src/binding/tests/sdk.rs, framework/src/executor/tests/mod.rs, protocol/src/traits/consensus.rs, protocol/src/traits/storage.rs
feature
* remove redundant wal transactions when do commit
* bump overlord version to 0.2.0-alpha.8
Fixes #
=> feat: remove redundant wal transactions when commit

examples/config-1.toml, examples/config-2.toml, examples/config-3.toml, examples/config-4.toml, examples/gensis.toml
=> chore: Add nodes config for the four nodes

src/default_start.rs
feat
Integrate actix with tokio runtime.
Fixes #
=> feat: Supports actix in tokio

examples/muta-chain.rs, src/default_start.rs, src/lib.rs
fix
hangs up running on single core
Fixes #
=> fix(muta): hangs up running on single core environment

examples/muta-chain.rs, src/default_start.rs, src/lib.rs
Reverts nervosnetwork/muta#201
=> Revert "fix(muta): hangs up running on single core environment"

core/api/src/config.rs, core/api/src/lib.rs, devtools/chain/config.toml, examples/config-1.toml, examples/config-2.toml, examples/config-3.toml, examples/config-4.toml, src/config.rs, src/default_start.rs
New feature.
The default actix payload size limit is 16K, which may be not enough for deploying contract.
Make it configurable and set the default valut to 1MB.
Fixes #
=> feat: add actix payload size limit config

Cargo.toml, examples/muta-chain.rs, src/default_start.rs, src/lib.rs
fix
fix hangs up on one cpu core
Fixes #
=> fix(muta): hangs up on one cpu core

README.md, README_EN.md
=> docs: update readme

core/consensus/src/message.rs, core/mempool/src/adapter/message.rs, core/network/examples/buycopy.rs, core/network/src/error.rs, core/network/src/lib.rs, core/network/src/outbound/rpc.rs, core/network/src/protocols/transmitter.rs, core/network/src/reactor/mod.rs, core/network/src/rpc.rs, core/network/src/service.rs, protocol/src/traits/network.rs
add
BREAKING CHANGE: rpc remote server error response
Fixes #
=> feat(network): rpc remote server error response

core/consensus/src/engine.rs
bugfix
fix panic when start
Fixes #
=> fix: panic when start

core/consensus/src/engine.rs
refactor
change timestamp from second to millisecond
Fixes #
=> refactor: change timestamp to millisecond

core/consensus/Cargo.toml
=> chore: Update overlord to 0.2.0-alpha10

core/consensus/src/synchronization.rs, core/consensus/src/tests/synchronization.rs, devtools/chain/config.toml, src/config.rs, src/default_start.rs
feat
In a weak network environment, a single request for a large number of transactions causes the request to timeout
Splitting a large number of transactions into several requests can greatly alleviate this situation
Fixes #
=> feat(sync): Split a transaction in a block into multiple requests

core/consensus/Cargo.toml, core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/fixed_types.rs, core/consensus/src/lib.rs, core/consensus/src/synchronization.rs, core/consensus/src/wal.rs, core/consensus/src/wal_proto.rs, src/default_start.rs
feature
* Re-execute blocks from the latest exec_height to current_height to recover current status
Fixes #
=> feat: re-execute blocks to recover current status

src/default_start.rs
Bug fix
program hangs on `kill pid` it
=> fix: hang when kill it

core/consensus/src/adapter.rs
=> chore: Execution log

core/consensus/src/adapter.rs, core/consensus/src/engine.rs
refactor
* Change futures channel to tokio channel
* If exec queue is full, wait for a moment and re-commit block
Fixes #
=> refactor: change futures channel to tokio channel

README.md, devtools/chain/config.toml, devtools/docker/dockercompose/config-bft-1.toml, devtools/docker/dockercompose/config-bft-2.toml, devtools/docker/dockercompose/config-bft-3.toml, devtools/docker/dockercompose/config-bft-4.toml, devtools/docker/dockercompose/config-single.toml, examples/config-1.toml, examples/config-2.toml, examples/config-3.toml, examples/config-4.toml, src/config.rs
bug fix
Set default value for ConfigRocksDB, so that we don't need to add a new section "rocksdb" in configuration files.
Fixes #
=> fix(config): use serde(default) for rocksdb conf

core/consensus/src/engine.rs
chore
add log when update metadata
Fixes #
=> chore: add metadata log

core/consensus/src/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/synchronization.rs, core/consensus/src/tests/synchronization.rs, src/default_start.rs
bugfix
* set crypto info when synchronization
Fixes #
=> fix(sync): set crypto info when synchronization

Makefile
Fix ci
Use debug mode to build muta-example when run e2e test.
Fixes #
=> chore(ci): use debug mode to run e2e

Cargo.toml, built-in-services/util/Cargo.toml, built-in-services/util/src/lib.rs, built-in-services/util/src/tests/mod.rs, built-in-services/util/src/types.rs, examples/muta-chain.rs, framework/Cargo.toml, tests/e2e/jest.config.js, tests/e2e/sdk.test.ts
feature
add util service, add keccak256,verify in util service
Fixes #
=> feat(service):add keccak256,verify in util service

built-in-services/asset/Cargo.toml, built-in-services/asset/src/types.rs, protocol/Cargo.toml, protocol/src/types/block.rs, protocol/src/types/genesis.rs, protocol/src/types/primitive.rs, protocol/src/types/receipt.rs, protocol/src/types/transaction.rs
chore
**What this PR does / why we need it**: 
* bump muta codec derive version
Fixes #
=> chore: bump muta codec derive version

protocol/src/fixed_codec/primitive.rs
change
change the FixedCodec implementation for ethbloom
Fixes #
=> fix: FixedCodec implementation for logs bloom

core/mempool/src/map.rs, core/mempool/src/tx_cache.rs
bugfix
* check exsit before insert a transaction
Fixes #
=> fix(mempool): check exsit before insert a transaction

core/consensus/src/adapter.rs, core/consensus/src/synchronization.rs, core/consensus/src/tests/synchronization.rs, core/mempool/src/adapter/message.rs, core/mempool/src/adapter/mod.rs, core/mempool/src/lib.rs, core/mempool/src/tests/mod.rs, protocol/src/traits/consensus.rs, protocol/src/traits/mempool.rs, src/default_start.rs
fix
Fixed redundant requests while synchronizing blocks.
1. https://github.com/nervosnetwork/muta/pull/259#discussion_r416545078
2. https://github.com/nervosnetwork/muta/pull/259#discussion_r416545662
Fixes #
=> fix(sync): Avoid requesting redundant transactions

.travis.yml
fix ci
The default 10m timeout doesn't satisfy us anymore.
https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
Fixes #
=> fix(ci): Increase timeout in ci

core/network/Cargo.toml, core/network/src/connection/keeper.rs, core/network/src/connection/mod.rs
chore
upgrade tentacle to latest 0.3-alpha4
- fix memory leaks [related pr](https://github.com/nervosnetwork/p2p/pull/218)
- some performance optimization
Fixes #
=> chore(network): upgrade tentacle

core/consensus/src/message.rs, core/mempool/src/adapter/message.rs, core/network/Cargo.toml, core/network/examples/buycopy.rs, core/network/src/config.rs, core/network/src/error.rs, core/network/src/event.rs, core/network/src/message/mod.rs, core/network/src/peer_manager/mod.rs, core/network/src/peer_manager/peer.rs, core/network/src/peer_manager/test_manager.rs, core/network/src/peer_manager/trust_metric.rs, core/network/src/reactor/mod.rs, core/network/src/reactor/router.rs, core/network/src/service.rs, core/network/tests/gossip_test.rs, protocol/src/traits/mod.rs, protocol/src/traits/network.rs, src/config.rs, src/default_start.rs
feat
- Peer trust metric
- Disconnect and ban bad peers
Fixes #
=> feat(network): peer trust metric

core/network/src/peer_manager/mod.rs, core/network/src/peer_manager/shared.rs, core/network/src/peer_manager/test_manager.rs
fix
fix broken users_cast
Fixes #
=> fix(network): broken users_cast

core/mempool/Cargo.toml, core/mempool/src/adapter/message.rs, core/mempool/src/adapter/mod.rs, core/mempool/src/lib.rs, core/mempool/src/tests/mod.rs, protocol/src/traits/mempool.rs
feat
integrate trust metric
Fixes #
=> feat(mempool): integrate trust metric

core/consensus/Cargo.toml
chore
* upgrade overlord version that refactor the proposal collector
Fixes #
=> chore: upgrade overlord that refactor proposal collector

core/network/Cargo.toml, core/network/src/connection/keeper.rs
Downgrade tentacle
fix
downgrade tentacle
Fixes #
=> fix(network): reconnection fialure

common/apm/src/metrics.rs, common/apm/src/metrics/network.rs, core/network/Cargo.toml, core/network/src/common.rs, core/network/src/connection/control.rs, core/network/src/lib.rs, core/network/src/metrics.rs, core/network/src/outbound/rpc.rs, core/network/src/protocols/transmitter.rs, core/network/src/service.rs
feat
add network metrics
Fixes #
=> feat(network): add metrics

common/apm/src/metrics/api.rs, core/api/src/lib.rs
feat
add api get_block metrics
Fixes #
=> feat(apm): add api get_block metrics

common/apm/src/metrics/sync.rs
Fix
Fix duplicate name `muta_sync_time_cost_seconds` in metrics
Fixes #
=> fix(metrics): fix duplicate name

core/consensus/Cargo.toml, core/consensus/src/adapter.rs, core/mempool/src/lib.rs
=> chore: upgrade overlord version with tracing

common/apm/src/metrics/consensus.rs, core/consensus/src/adapter.rs, core/consensus/src/engine.rs, core/consensus/src/synchronization.rs
- Fix exponential_buckets arguments.
- Time cost: `exponential_buckets(0.05, 2.0, 10)` => `exponential_buckets(0.05, 1.5, 20)`
- Round: `exponential_buckets(0.05, 2.0, 10)` => `exponential_buckets(0.5, 1.5, 10)`
- Fix some wrong buried points
Fixes #
=> Fix(metrics): fix wrong buried in consensus

common/apm/Cargo.toml, core/network/src/message/mod.rs, core/network/src/outbound/gossip.rs, core/network/src/outbound/rpc.rs, core/network/src/reactor/mod.rs
feat
add trace to network message header
Fixes #
=> feat(network): add trace header to network msg

common/crypto/Cargo.toml, common/crypto/src/lib.rs, common/merkle/Cargo.toml, common/merkle/src/lib.rs, core/consensus/src/wal.rs, core/mempool/src/tests/mempool.rs, core/storage/src/tests/storage.rs
feat
* add some benchmarks and the results
Fixes #
=> feat(bench) add some benchmarks

core/consensus/src/consensus.rs
feat
trace height and round in OverlordMsg
Fixes #
=> feat(apm): tracing height and round in OverlordMsg

core/network/src/outbound/gossip.rs, core/network/src/outbound/rpc.rs, core/network/src/peer_manager/mod.rs
chore
debug missing network trace id
Fixes #
=> chore: log info on missing network message trace id

core/mempool/src/lib.rs
refactor
If the transaction is already in the `mempool` cache, we can skip validation.
This will greatly improve the synchronization efficiency when height - 1.
Fixes #
=> refactor(mempool): Avoid duplicate validation transactions when sync

common/apm/src/metrics/network.rs, core/consensus/src/engine.rs, core/network/src/outbound/gossip.rs, core/network/src/outbound/rpc.rs, core/network/src/reactor/router.rs
feat
split monitor network url with multiple labels to make it more clear
Fixes #
=> feat: split monitor network url 

core/storage/src/lib.rs
=> chore(tracing): Avoid traces of high-frequency functions

core/storage/src/lib.rs, tests/e2e/package.json
=> fix master ci failure

common/apm/src/metrics.rs, common/apm/src/metrics/consensus.rs, common/apm/src/metrics/network.rs, common/apm/src/metrics/storage.rs, core/consensus/src/engine.rs, core/consensus/src/synchronization.rs, core/network/src/outbound/gossip.rs, core/storage/src/adapter/rocks.rs, core/storage/src/lib.rs
feat
supported storage insert and iter apm
Fixes #
=> feat: supported storage apm

CHANGELOG.md
add changelog for release
add changelog for release
Fixes #
=> add changelog to release

built-in-services/asset/src/tests/mod.rs, built-in-services/metadata/src/tests/mod.rs, built-in-services/util/src/tests/mod.rs, framework/src/binding/sdk/mod.rs, framework/src/binding/tests/sdk.rs, framework/src/executor/mod.rs
fix
fix DefaultServiceSDK typo
Fixes #
=> fix(framework)!: DefalutServiceSDK typo

OWNERS, OWNERS_ALIASES
/kind chore
Update OWNERS
Fixes #
=> chore: Update OWNERS

tests/trust_metric_all/common.rs, tests/trust_metric_all/mod.rs, tests/trust_metric_all/node/client_node.rs, tests/trust_metric_all/node/full_node.rs, tests/trust_metric_all/node/full_node/builder.rs, tests/trust_metric_all/node/full_node/default_start.rs
fix
More reliable full node exit check in trust metric integration tests
Fixes #
=> fix(trust_metric_test): unreliable full node exit check

core/network/Cargo.toml, core/network/src/connection/control.rs, core/network/src/connection/keeper.rs, core/network/src/connection/mod.rs, core/network/src/error.rs, core/network/src/event.rs, core/network/src/peer_manager/mod.rs, core/network/src/peer_manager/save_restore.rs
chore
- fix memory leakage
- optimize performance
Fixes #
=> chore(network): upgrade tentacle to v0.3.0alpha5

Cargo.toml, Makefile, core/network/src/lib.rs, core/network/src/peer_manager/diagnostic.rs, core/network/src/peer_manager/mod.rs, core/network/src/service.rs, protocol/src/traits/network.rs, tests/trust_metric_all/common.rs, tests/trust_metric_all/consensus.rs, tests/trust_metric_all/mempool.rs, tests/trust_metric_all/mod.rs, tests/trust_metric_all/node.rs, tests/trust_metric_all/node/client_node.rs, tests/trust_metric_all/node/diagnostic.rs, tests/trust_metric_all/node/full_node.rs, tests/trust_metric_all/node/full_node/builder.rs, tests/trust_metric_all/node/full_node/default_start.rs, tests/trust_metric_all/node/sync.rs
refactor
Sync full node and client node using event instead of timeout guess game.
This should be more reliable.
To make sure 100% pass, run trust metric tests one by one.
Fix #334 
Fixes #
=> refactor(tests): trust metric integration tests

core/consensus/Cargo.toml, core/consensus/src/status.rs, core/consensus/src/tests/mod.rs, core/consensus/src/tests/status.rs, core/consensus/src/tests/synchronization.rs
test
* Add unit tests of current consensus status in consensus module.
Fixes #
=> test(consensus): add unit test of current consensus status

.github/semantic.yml
ci
follow angular commit message
Fixes #
=> ci: Add semantic config

binding-macro/src/service.rs, binding-macro/tests/mod.rs, framework/src/executor/tests/test_service.rs, protocol/src/traits/binding.rs
feat!: add tx_hook return type
this could imply the result of tx_hook
=> feat(framework)!: Add return type ServiceResponse<String> for tx_hook

charts/deploy-chaos/values.yaml, jenkins-x-chaos.yml
ci
- Benchmark pressure tests correctly when running chaos test.
- If chaos shows an exception, the task should show failure.
Fixes #
=> ci: Fix chaos test

core/mempool/src/adapter/mod.rs
perf
* make verifying signatures in mempool parallelly.
Fixes #
=> perf(mempool): parallel verifying signatures in mempool

framework/src/executor/mod.rs, framework/src/executor/tests/framework.rs, framework/src/executor/tests/framework_genesis_services.toml, framework/src/executor/tests/mod.rs
fix: fix the logic to deal with tx_hook and tx_body
fix: fix executor, change the logic/sequence of dealing with tx hooks and tx body
this logic should fit normal business better
=> fix(executor): The logic to deal with tx_hook and tx_body

core/consensus/Cargo.toml
=> feat: update overlord version

built-in-services/asset/src/lib.rs, built-in-services/authorization/src/lib.rs, built-in-services/metadata/src/lib.rs, built-in-services/multi-signature/src/lib.rs, built-in-services/util/src/lib.rs, devtools/chain/genesis.toml, framework/src/executor/tests/framework.rs, framework/src/executor/tests/test_service.rs
refactor
- increacing `cycles_limit` from 100000 to  0xffffffff avoid errors in the example
- make the `cycles_limit` more [readable](https://en.wikipedia.org/wiki/Decimal_separator)
Fixes #
=> refactor: increacing `cycles_limit` to avoid errors in the example

jenkins-x.yml
Because big bro Hui don't like it
=> ci: Disabled auto tag version

core/consensus/Cargo.toml, core/consensus/src/engine.rs, core/consensus/src/lib.rs, core/consensus/src/tests/engine.rs, core/consensus/src/tests/mod.rs, core/consensus/src/tests/status.rs
fix
Return an error when committing an outdated block, avoid panic here.
Fixes #
=> fix(consensus): return an error when committing an outdated block

devtools/chain/genesis.toml, docs/build/gql_api.sh, docs/graphql_api.md
doc: fix gql_api.sh and update graphql_api.md
update graphql doc
=> docs: fix gql_api.sh and update graphql_api.md

README.md, README_CN.md
docs
Fixed links in README.md
Fixes #
=> docs: Fix links in README.md

README.md, README_CN.md, docs/resources.md
List available resources for Muta
Fixes #
=> docs:  available resources for muta

framework/Cargo.toml, framework/src/binding/state/trie_db.rs
dependencies
Keep it consistent with the `storage`
Fixes #
=> build(framework): Update rocksdb to v0.14

common/apm/src/lib.rs, common/apm/src/metrics.rs
fix
Return the correct time
Fixes #
=> fix(apm): Return the correct time

common/apm/src/metrics/network.rs, core/network/src/peer_manager/mod.rs, core/network/src/protocols/ping/behaviour.rs, core/network/src/protocols/ping/protocol.rs, core/network/src/protocols/transmitter/protocol.rs, core/network/src/reactor/mod.rs
New metrics:
- current processing message gauge
- current processing message gauge by ip
- connected peers
- ip ping in ms
- ip disconnected count
- outbound connecting peers
- unidentified connection
- saved peers
- consensus peers gauge
- connected consensus peers
Fixes #
Ref #
=> feat(network): add more metrics

Cargo.toml, core/network/Cargo.toml
Add a feature to enable tentacle metrics
Fixes #
Ref #
=> feat(network): add tentacle_metrics feature

charts/deploy-chaos/templates/muta-benchmark.yaml
Set`concurrencyPolicy= Replace ` to  benchmark.yaml.
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
Fixes #
Ref #
=> ci: Add concurrencyPolicy for benchmark

core/consensus/Cargo.toml
refactor: update to latest overlord
overlord fix random leader.
and overlord verify proposer before filter proposal.
docs: N/A
toolchain: N/A
=> refactor: update to latest overlord

core/consensus/src/engine.rs
refactor consensus log
Fixes #
Ref #
=> refactor(consensus): change an error log info when get block

core/network/src/peer_manager/mod.rs
Fix network metric
Fixes #
Ref #
=> fix(network): double decrease connecting gauge

common/apm/README.md
Metrics docs for promethues 
Fixes #
Ref #
=> docs: Metrics docs for promethues 

common/apm/README.md, common/apm/src/metrics/consensus.rs, core/consensus/src/engine.rs, core/consensus/src/status.rs
Add executing block number gauge to apm.
Fixes #
Ref #
=> feat(apm): add executing block num to apm

core/consensus/src/adapter.rs, core/consensus/src/lib.rs, devtools/chain/config.toml, src/config.rs, src/default_start.rs, tests/common/node/config.rs, tests/common/node/full_node/default_start.rs
change the overlord gap into configurable
Fixes #
Ref https://github.com/nervosnetwork/muta-docs/pull/63
=> refactor: change the overlord gap into configurable

byzantine/src/invalid_types.rs, core/consensus/src/fixed_types.rs, core/mempool/src/adapter/mod.rs, core/network/src/outbound/gossip.rs, core/network/src/outbound/rpc.rs, core/network/src/reactor/mod.rs, protocol/src/traits/network.rs
Remove unnecessary async context switch.
Fixes #
Ref #
=> feat(protocol): network MessageCodec to sync

byzantine/README.md, byzantine/generators.toml, byzantine/src/behaviors.rs, byzantine/src/commander.rs, byzantine/src/invalid_types.rs, byzantine/src/utils.rs, byzantine/src/worker.rs, examples/config-1.toml, examples/config-2.toml, examples/config-3.toml, examples/config-4.toml
1. fix configs in examples
2. fix transaction construction in byzantine test
Fixes #
Ref #
=> fix: update example configs, fix send transaction in byzantine

Cargo.toml, binding-macro/Cargo.toml, built-in-services/asset/Cargo.toml, built-in-services/metadata/Cargo.toml, built-in-services/multi-signature/Cargo.toml, built-in-services/util/Cargo.toml, common/channel/Cargo.toml, common/config-parser/Cargo.toml, common/crypto/Cargo.toml, common/logger/Cargo.toml, common/merkle/Cargo.toml, common/pubsub/Cargo.toml, core/api/Cargo.toml, core/consensus/Cargo.toml, core/mempool/Cargo.toml, core/network/Cargo.toml, core/storage/Cargo.toml, devtools/keypair/Cargo.toml, framework/Cargo.toml, protocol/Cargo.toml
build: build muta v0.2.0-rc.2
Ref #
Breaking Change
The logic of executor changes, it may affect failure txs and state diverses.
=> build!: Release muta v0.2.0-rc.2

Cargo.toml, binding-macro/Cargo.toml, built-in-services/asset/Cargo.toml, built-in-services/metadata/Cargo.toml, built-in-services/multi-signature/Cargo.toml, built-in-services/util/Cargo.toml, common/channel/Cargo.toml, common/config-parser/Cargo.toml, common/crypto/Cargo.toml, common/logger/Cargo.toml, common/merkle/Cargo.toml, common/pubsub/Cargo.toml, core/api/Cargo.toml, core/consensus/Cargo.toml, core/mempool/Cargo.toml, core/network/Cargo.toml, core/storage/Cargo.toml, devtools/keypair/Cargo.toml, framework/Cargo.toml, protocol/Cargo.toml
build: build muta v0.2.0-rc.2.1
=> build: build muta v0.2.0-rc.2.1

byzantine/Cargo.toml, core/consensus/Cargo.toml, core/consensus/src/consensus.rs, protocol/Cargo.toml, src/default_start.rs, tests/common/node/full_node/default_start.rs
* upgrade overlord version to v0.2.0
Fixes #
Ref #
=> refactor(consensus): upgrade overlord version to v0.2.0

common/logger/README.md, common/logger/src/lib.rs
Add structured api document to logger README
Fixes #
Ref #
=> fix(logger): add structured api

CHANGELOG/CHANGELOG-0.2.md, Cargo.toml, binding-macro/Cargo.toml, built-in-services/asset/Cargo.toml, built-in-services/authorization/Cargo.toml, built-in-services/metadata/Cargo.toml, built-in-services/multi-signature/Cargo.toml, built-in-services/util/Cargo.toml, byzantine/Cargo.toml, common/apm/Cargo.toml, common/channel/Cargo.toml, common/config-parser/Cargo.toml, common/crypto/Cargo.toml, common/logger/Cargo.toml, common/merkle/Cargo.toml, common/pubsub/Cargo.toml, core/api/Cargo.toml, core/cli/Cargo.toml, core/consensus/Cargo.toml, core/mempool/Cargo.toml, core/network/Cargo.toml, core/run/Cargo.toml, core/storage/Cargo.toml, devtools/keypair/Cargo.toml, examples/muta-chain.rs, framework/Cargo.toml, protocol/Cargo.toml
build: build muta v0.2.0
No thing special
=> build: Release v0.2.0

common/apm/src/metrics/consensus.rs, core/consensus/src/engine.rs
Metric proposal ordered transaction length and sync transaction length.
Fixes #
Ref #
=> feat(consensus): metric proposal ordered tx len and sync tx len

core/cli/src/lib.rs, core/cli/src/tests/mod.rs, examples/muta-chain.rs, src/lib.rs
feat(cli): add config for default config and genesis path
give dimension for default config and genesis path
=> feat(cli): add config for default config and genesis path

Cargo.toml, binding-macro/Cargo.toml, built-in-services/asset/Cargo.toml, built-in-services/authorization/Cargo.toml, built-in-services/metadata/Cargo.toml, built-in-services/multi-signature/Cargo.toml, built-in-services/util/Cargo.toml, byzantine/Cargo.toml, common/apm/Cargo.toml, common/channel/Cargo.toml, common/config-parser/Cargo.toml, common/crypto/Cargo.toml, common/logger/Cargo.toml, common/merkle/Cargo.toml, common/pubsub/Cargo.toml, core/api/Cargo.toml, core/cli/Cargo.toml, core/consensus/Cargo.toml, core/mempool/Cargo.toml, core/network/Cargo.toml, core/run/Cargo.toml, core/storage/Cargo.toml, devtools/keypair/Cargo.toml, examples/muta-chain.rs, framework/Cargo.toml, protocol/Cargo.toml
=> build: bump version to v0.2.1

README.md, README_CN.md
=> docs: update image src in README

common/apm/Cargo.toml
=> refactor(apm): upgrade rust prometheus version
